
constructs_in_order = [
	"Passive suicidal ideation",
	"Active suicidal ideation & suicidal planning",
	"Lethal means for suicide",
	"Direct self-injury",
	"Suicide exposure",
	"Other suicidal language",
	'Hospitalization',


	"Loneliness & isolation",
	"Social withdrawal",
	"Relationship issues",
	"Relationships & kinship",
	"Bullying",
	"Sexual abuse & harassment",
	"Physical abuse & violence",
	"Aggression & irritability",
	"Alcohol use",
	"Other substance use",
	"Impulsivity",
	"Defeat & feeling like a failure",
	"Burdensomeness",
	"Shame, self-disgust, & worthlessness",
	"Guilt",
	"Anxiety",
	"Panic",
	"Trauma & PTSD",
	"Agitation",
	"Rumination",
	"Entrapment & desire to escape",
    
	"Depressed mood",
	"Anhedonia & uninterested",
	"Emotional pain & psychache",
	"Grief & bereavement",
	"Existential meaninglessness & purposelessness",
	"Emptiness",
	"Hopelessness",
	
	"Perfectionism",
	"Fatigue & tired",
	"Sleep issues",
	"Psychosis & schizophrenia",
	"Bipolar Disorder",
	"Borderline Personality Disorder",
	"Eating disorders",
	"Physical health issues & disability",
	"Incarceration",
	"Poverty & homelessness",
	"Gender & sexual identity",
	"Discrimination",
	"Finances & work stress",
	"Barriers to treatment",
	
	"Mental health treatment",
]

# order for each annotator
constructs_importance = [
	"Passive suicidal ideation",
	"Active suicidal ideation & suicidal planning",
    "Other suicidal language",
	"Direct self-injury",
	"Lethal means for suicide",
	"Suicide exposure",
    'Hospitalization',

	"Depressed mood",
	"Anhedonia & uninterested",
	"Emotional pain & psychache",
	"Grief & bereavement",
	"Fatigue & tired",
	"Emptiness",
	"Hopelessness",
    "Relationship issues",
	"Aggression & irritability",
	"Physical abuse & violence",	
	"Sexual abuse & harassment",
	"Anxiety",
	"Trauma & PTSD",    
    "Mental health treatment",
    
	"Guilt",
	"Borderline Personality Disorder",
	"Panic",
	"Agitation",
	"Entrapment & desire to escape",
    "Burdensomeness",
	"Rumination",
	"Shame, self-disgust, & worthlessness",
	"Loneliness & isolation",
	"Bipolar Disorder",
	"Psychosis & schizophrenia",
    "Eating disorders",
	
    "Impulsivity",
	"Existential meaninglessness & purposelessness",
	"Bullying",
    "Sleep issues",
	"Defeat & feeling like a failure",
	"Perfectionism",
    "Social withdrawal",
    "Barriers to treatment",
    
	"Discrimination",
	"Physical health issues & disability",	
	"Incarceration",
    "Poverty & homelessness",
    "Gender & sexual identity",
    "Finances & work stress",
    "Alcohol use",
	"Other substance use",
    "Relationships & kinship",
    
]


# order for each annotator
constructs_kb = [
	"Passive suicidal ideation",
	"Active suicidal ideation & suicidal planning",
    "Other suicidal language",
	"Direct self-injury",
	"Lethal means for suicide",
	"Suicide exposure",
    'Hospitalization',
    
	"Anxiety",
    "Panic",
	"Agitation",
	"Trauma & PTSD",    
    "Mental health treatment",

	"Depressed mood",
	"Anhedonia & uninterested",
	"Emotional pain & psychache",
	"Grief & bereavement",
	"Fatigue & tired",
	"Emptiness",
	"Hopelessness",
    "Relationship issues",
	"Aggression & irritability",
	"Physical abuse & violence",	
	"Sexual abuse & harassment",
    
	"Borderline Personality Disorder",
    "Shame, self-disgust, & worthlessness",
    "Guilt",
	"Entrapment & desire to escape",
    "Burdensomeness",
	"Rumination",
	
	"Loneliness & isolation",
	"Bipolar Disorder",
	"Psychosis & schizophrenia",
    "Eating disorders",
	
    "Impulsivity",
	"Existential meaninglessness & purposelessness",
	"Bullying",
    "Sleep issues",
	"Defeat & feeling like a failure",
	"Perfectionism",
    "Social withdrawal",
    "Barriers to treatment",
    
	"Discrimination",
	"Physical health issues & disability",	
	"Incarceration",
    "Poverty & homelessness",
    "Gender & sexual identity",
    "Finances & work stress",
    "Alcohol use",
	"Other substance use",
    "Relationships & kinship",
    
]

constructs_or = [
	"Passive suicidal ideation",
	"Active suicidal ideation & suicidal planning",
    "Other suicidal language",
	"Direct self-injury",
	"Lethal means for suicide",
	"Suicide exposure",
    'Hospitalization',
    
	"Depressed mood",
	"Anhedonia & uninterested",
	"Emotional pain & psychache",
	"Grief & bereavement",
	"Fatigue & tired",
	"Emptiness",
	"Hopelessness",
    "Relationship issues",
	"Aggression & irritability",
	"Physical abuse & violence",	
	"Sexual abuse & harassment",
    
	"Anxiety",
    "Panic",
	"Agitation",
	"Trauma & PTSD",    
    "Mental health treatment",
    
	"Borderline Personality Disorder",
    "Shame, self-disgust, & worthlessness",
    "Guilt",
	"Entrapment & desire to escape",
    "Burdensomeness",
	"Rumination",
	"Loneliness & isolation",
	"Bipolar Disorder",
	"Psychosis & schizophrenia",
    "Eating disorders",
	
    "Impulsivity",
	"Existential meaninglessness & purposelessness",
	"Bullying",
    "Sleep issues",
	"Defeat & feeling like a failure",
	"Perfectionism",
    "Social withdrawal",
    "Barriers to treatment",
    
	"Discrimination",
	"Physical health issues & disability",	
	"Incarceration",
    "Poverty & homelessness",
    "Gender & sexual identity",
    "Finances & work stress",
    "Alcohol use",
	"Other substance use",
    "Relationships & kinship",
    
]



constructs_dc = [
	"Passive suicidal ideation",
	"Active suicidal ideation & suicidal planning",
    "Other suicidal language",
	"Direct self-injury",
	"Lethal means for suicide",
	"Suicide exposure",
    'Hospitalization',
    
	"Borderline Personality Disorder",
    "Shame, self-disgust, & worthlessness",
    "Guilt",
	"Entrapment & desire to escape",
    "Burdensomeness",
	"Rumination",
	"Loneliness & isolation",
	"Bipolar Disorder",
	"Psychosis & schizophrenia",
    "Eating disorders",
    
	"Depressed mood",
	"Anhedonia & uninterested",
	"Emotional pain & psychache",
	"Grief & bereavement",
	"Fatigue & tired",
	"Emptiness",
	"Hopelessness",

    "Relationship issues",
	"Aggression & irritability",
	"Physical abuse & violence",	
	"Sexual abuse & harassment",
    
	"Anxiety",
    "Panic",
	"Agitation",
	"Trauma & PTSD",    
    "Mental health treatment",
    
    
	"Impulsivity",
	"Existential meaninglessness & purposelessness",
	"Bullying",
    "Sleep issues",
	"Defeat & feeling like a failure",
	"Perfectionism",
    "Social withdrawal",
    "Barriers to treatment",
    
	"Discrimination",
	"Physical health issues & disability",	
	"Incarceration",
    "Poverty & homelessness",
    "Gender & sexual identity",
    "Finances & work stress",
    "Alcohol use",
	"Other substance use",
    "Relationships & kinship",
    
]




